"""
Shared state of the multi-agent system following the architecture design.
"""

from __future__ import annotations
from typing import Literal, Optional, List, Dict, Any
from langgraph.graph import MessagesState


class GraphState(MessagesState):
    """Graph state following the architecture design from architecture.md."""

    # Core fields from architecture
    goal: Optional[str]  # Initial user request
    todo_list: Optional[List[Dict[str, Any]]]  # List of tasks to be performed by agents
    results: Optional[Dict[str, Any]]  # Dictionary to store raw results from agents
    error_info: Optional[Dict[str, Any]]  # Contains details of any errors encountered
    root_cause_analysis: Optional[Dict[str, Any]]  # Structured output from the Debugger
    final_response: Optional[
        str
    ]  # User-facing message generated by Response Synthesizer

    # Routing and flow control
    route: Optional[
        Literal[
            "api_operator",
            "debugger",
            "knowledge_assistant",
            "response_synthesizer",
            "done",
        ]
    ]
    next_agent: Optional[str]  # Next agent to invoke

    # Additional fields for knowledge storage
    knowledge_summary: Optional[List[Dict[str, Any]]]
